{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "gpuType": "T4"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "# ColabでPhysicsNeMoを動かす"
      ],
      "metadata": {
        "id": "jFK6Qj4j5NbZ"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "GoogleDriveへのアクセス権限が必要（アクセス許可をします．）\n",
        "\n",
        "GoogleDrive内にphysicsnemo_workspaceという名前のフォルダを作成し，その中にこのmain.ipynbを置く．\n",
        "\n",
        "ランタイムのタイプをT4 GPUに変更（使いすぎると使用不可になります，なりました．）"
      ],
      "metadata": {
        "id": "XJSuEFfw5x3P"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "### GoogleDriveをマウントし，Drive内にPhysicsNeMoをクローン"
      ],
      "metadata": {
        "id": "uqdyvhWC5acm"
      }
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "6I1vIbjl1zBu",
        "outputId": "2534b88d-045f-48b1-a42d-6328abf59f58"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n",
            "/content/drive/MyDrive/physicsnemo_workspace\n",
            "fatal: destination path 'physicsnemo' already exists and is not an empty directory.\n",
            "fatal: destination path 'physicsnemo-sym' already exists and is not an empty directory.\n"
          ]
        }
      ],
      "source": [
        "from google.colab import drive\n",
        "import os\n",
        "\n",
        "drive.mount(\"/content/drive\")\n",
        "\n",
        "%cd \"/content/drive/MyDrive/physicsnemo_workspace\"\n",
        "\n",
        "!git clone https://github.com/NVIDIA/physicsnemo.git\n",
        "!git clone https://github.com/NVIDIA/physicsnemo-sym.git"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "これでGoogleDriveの`マイドライブ/physicsnemo_workspace/`の下に`physicsnemo`と`physicsnemo-sym`がダウンロードされる．"
      ],
      "metadata": {
        "id": "n8bkON2u6M1U"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "### PhysicsNeMoのインストール"
      ],
      "metadata": {
        "id": "3vS61by95sfK"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "#### ソースコードからインストールしようとしたがphysicsnemo-symのほうがエラーが発生してできなかった．\n",
        "\n",
        "```\n",
        "Obtaining file:///content/drive/MyDrive/physicsnemo_workspace/physicsnemo-sym\n",
        "  Installing build dependencies ... done\n",
        "  Checking if build backend supports build_editable ... done\n",
        "  error: subprocess-exited-with-error\n",
        "  \n",
        "  × Getting requirements to build editable did not run successfully.\n",
        "  │ exit code: 1\n",
        "  ╰─> See above for output.\n",
        "  \n",
        "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
        "  Getting requirements to build editable ... error\n",
        "error: subprocess-exited-with-error\n",
        "\n",
        "× Getting requirements to build editable did not run successfully.\n",
        "│ exit code: 1\n",
        "╰─> See above for output.\n",
        "\n",
        "note: This error originates from a subprocess, and is likely not a problem with pip.\n",
        "```\n",
        "\n"
      ],
      "metadata": {
        "id": "Y-rCv3R0FZxu"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "\n",
        "\n",
        "```\n",
        "!sudo add-apt-repository -y ppa:deadsnakes/ppa\n",
        "!sudo apt-get -y update\n",
        "!sudo apt-get -y install python3.10\n",
        "!sudo apt-get -y install python3.10-dev\n",
        "!sudo apt-get -y install python3-pip\n",
        "!sudo apt-get -y install python3.10-distutils\n",
        "\n",
        "!python3.10 -m pip install --upgrade setuptools\n",
        "!python3.10 -m pip install --upgrade pip\n",
        "!python3.10 -m pip install --upgrade distlib\n",
        "\n",
        "%cd \"/content/drive/MyDrive/physicsnemo_workspace\"\n",
        "%cd \"physicsnemo\"\n",
        "!python3.10 -m pip install -e .\n",
        "%cd \"../physicsnemo-sym\"\n",
        "!python3.10 -m pip install Cython\n",
        "!python3.10 -m pip install -e .\n",
        "```\n",
        "\n"
      ],
      "metadata": {
        "id": "pU-dNVVyJkyl"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "### physicsnemoのインストール（PyPI）\n",
        "\n",
        "physicsnemo-symのインストールでセッションの再起動が求められる（かも）"
      ],
      "metadata": {
        "id": "gf6fSdc-9xCS"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "%cd \"/content/drive/MyDrive/physicsnemo_workspace\"\n",
        "!pip install nvidia-physicsnemo\n",
        "!pip install Cython\n",
        "!pip install nvidia-physicsnemo-sym --no-build-isolation"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "pbxrdUsj6RO0",
        "outputId": "34bca926-0142-43c3-8e13-007aa26c1743"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content/drive/MyDrive/physicsnemo_workspace\n",
            "Requirement already satisfied: nvidia-physicsnemo in /usr/local/lib/python3.11/dist-packages (1.1.0)\n",
            "Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (2025.4.26)\n",
            "Requirement already satisfied: fsspec>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (2025.5.1)\n",
            "Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (2.0.2)\n",
            "Requirement already satisfied: onnx>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (1.18.0)\n",
            "Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (24.2)\n",
            "Requirement already satisfied: s3fs>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (2025.5.1)\n",
            "Requirement already satisfied: setuptools>=77.0.3 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (80.9.0)\n",
            "Requirement already satisfied: timm>=0.9.12 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (1.0.15)\n",
            "Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (2.6.0+cu124)\n",
            "Requirement already satisfied: tqdm>=4.60.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (4.67.1)\n",
            "Requirement already satisfied: treelib>=1.2.5 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (1.7.1)\n",
            "Requirement already satisfied: xarray>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (2025.3.1)\n",
            "Requirement already satisfied: zarr>=2.14.2 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo) (3.0.8)\n",
            "Requirement already satisfied: protobuf>=4.25.1 in /usr/local/lib/python3.11/dist-packages (from onnx>=1.14.0->nvidia-physicsnemo) (5.29.5)\n",
            "Requirement already satisfied: typing_extensions>=4.7.1 in /usr/local/lib/python3.11/dist-packages (from onnx>=1.14.0->nvidia-physicsnemo) (4.14.0)\n",
            "Requirement already satisfied: aiobotocore<3.0.0,>=2.5.4 in /usr/local/lib/python3.11/dist-packages (from s3fs>=2023.5.0->nvidia-physicsnemo) (2.22.0)\n",
            "Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from s3fs>=2023.5.0->nvidia-physicsnemo) (3.11.15)\n",
            "Requirement already satisfied: torchvision in /usr/local/lib/python3.11/dist-packages (from timm>=0.9.12->nvidia-physicsnemo) (0.21.0+cu124)\n",
            "Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from timm>=0.9.12->nvidia-physicsnemo) (6.0.2)\n",
            "Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.11/dist-packages (from timm>=0.9.12->nvidia-physicsnemo) (0.32.4)\n",
            "Requirement already satisfied: safetensors in /usr/local/lib/python3.11/dist-packages (from timm>=0.9.12->nvidia-physicsnemo) (0.5.3)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (3.18.0)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (3.5)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (3.1.6)\n",
            "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (12.4.127)\n",
            "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (12.4.127)\n",
            "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (12.4.127)\n",
            "Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (9.1.0.70)\n",
            "Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (12.4.5.8)\n",
            "Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (11.2.1.3)\n",
            "Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (10.3.5.147)\n",
            "Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (11.6.1.9)\n",
            "Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (12.3.1.170)\n",
            "Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (0.6.2)\n",
            "Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (2.21.5)\n",
            "Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (12.4.127)\n",
            "Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (12.4.127)\n",
            "Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (3.2.0)\n",
            "Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo) (1.13.1)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.4.0->nvidia-physicsnemo) (1.3.0)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from treelib>=1.2.5->nvidia-physicsnemo) (1.17.0)\n",
            "Requirement already satisfied: pandas>=2.1 in /usr/local/lib/python3.11/dist-packages (from xarray>=2023.1.0->nvidia-physicsnemo) (2.2.2)\n",
            "Requirement already satisfied: donfig>=0.8 in /usr/local/lib/python3.11/dist-packages (from zarr>=2.14.2->nvidia-physicsnemo) (0.8.1.post1)\n",
            "Requirement already satisfied: numcodecs>=0.14 in /usr/local/lib/python3.11/dist-packages (from numcodecs[crc32c]>=0.14->zarr>=2.14.2->nvidia-physicsnemo) (0.16.1)\n",
            "Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo) (0.12.0)\n",
            "Requirement already satisfied: botocore<1.37.4,>=1.37.2 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo) (1.37.3)\n",
            "Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo) (2.9.0.post0)\n",
            "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo) (1.0.1)\n",
            "Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo) (6.4.4)\n",
            "Requirement already satisfied: wrapt<2.0.0,>=1.10.10 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo) (1.17.2)\n",
            "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo) (2.6.1)\n",
            "Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo) (1.3.2)\n",
            "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo) (25.3.0)\n",
            "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo) (1.6.0)\n",
            "Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo) (0.3.1)\n",
            "Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo) (1.20.0)\n",
            "Requirement already satisfied: crc32c>=2.7 in /usr/local/lib/python3.11/dist-packages (from numcodecs[crc32c]>=0.14->zarr>=2.14.2->nvidia-physicsnemo) (2.7.1)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.1->xarray>=2023.1.0->nvidia-physicsnemo) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.1->xarray>=2023.1.0->nvidia-physicsnemo) (2025.2)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->timm>=0.9.12->nvidia-physicsnemo) (2.32.3)\n",
            "Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->timm>=0.9.12->nvidia-physicsnemo) (1.1.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.4.0->nvidia-physicsnemo) (3.0.2)\n",
            "Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.11/dist-packages (from torchvision->timm>=0.9.12->nvidia-physicsnemo) (11.2.1)\n",
            "Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.11/dist-packages (from botocore<1.37.4,>=1.37.2->aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo) (2.4.0)\n",
            "Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.11/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo) (3.10)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub->timm>=0.9.12->nvidia-physicsnemo) (3.4.2)\n",
            "Requirement already satisfied: Cython in /usr/local/lib/python3.11/dist-packages (3.0.12)\n",
            "Requirement already satisfied: nvidia-physicsnemo-sym in /usr/local/lib/python3.11/dist-packages (2.1.0)\n",
            "Requirement already satisfied: Cython>=0.29 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (3.0.12)\n",
            "Requirement already satisfied: chaospy>=4.3.7 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (4.3.18)\n",
            "Requirement already satisfied: h5py>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (3.13.0)\n",
            "Requirement already satisfied: hydra-core>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (1.3.2)\n",
            "Requirement already satisfied: mistune>=2.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (3.1.3)\n",
            "Requirement already satisfied: ninja in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (1.11.1.4)\n",
            "Requirement already satisfied: notebook>=7.2.2 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (7.4.3)\n",
            "Requirement already satisfied: numpoly<=1.3.4 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (1.3.4)\n",
            "Requirement already satisfied: numpy-stl>=2.16 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (3.2.0)\n",
            "Requirement already satisfied: nvidia-physicsnemo>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (1.1.0)\n",
            "Requirement already satisfied: opencv-python>=4.8.1.78 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (4.11.0.86)\n",
            "Requirement already satisfied: pillow>=10.3 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (11.2.1)\n",
            "Requirement already satisfied: pint>=0.19.2 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (0.24.4)\n",
            "Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (1.6.1)\n",
            "Requirement already satisfied: symengine>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (0.14.1)\n",
            "Requirement already satisfied: sympy>=1.12 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (1.13.1)\n",
            "Requirement already satisfied: tensorboard>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (2.18.0)\n",
            "Requirement already satisfied: termcolor>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (3.1.0)\n",
            "Requirement already satisfied: timm>=1.0.3 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (1.0.15)\n",
            "Requirement already satisfied: torch-optimizer>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (0.3.0)\n",
            "Requirement already satisfied: transforms3d>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (0.4.2)\n",
            "Requirement already satisfied: typing<3.8,>=3.7 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (3.7.4.3)\n",
            "Requirement already satisfied: vtk>=9.2.6 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo-sym) (9.4.2)\n",
            "Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.11/dist-packages (from chaospy>=4.3.7->nvidia-physicsnemo-sym) (2.0.2)\n",
            "Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from chaospy>=4.3.7->nvidia-physicsnemo-sym) (1.15.3)\n",
            "Requirement already satisfied: setuptools>=40.9.0 in /usr/local/lib/python3.11/dist-packages (from chaospy>=4.3.7->nvidia-physicsnemo-sym) (80.9.0)\n",
            "Requirement already satisfied: omegaconf<2.4,>=2.2 in /usr/local/lib/python3.11/dist-packages (from hydra-core>=1.2.0->nvidia-physicsnemo-sym) (2.3.0)\n",
            "Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.11/dist-packages (from hydra-core>=1.2.0->nvidia-physicsnemo-sym) (4.9.3)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from hydra-core>=1.2.0->nvidia-physicsnemo-sym) (24.2)\n",
            "Requirement already satisfied: jupyter-server<3,>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from notebook>=7.2.2->nvidia-physicsnemo-sym) (2.16.0)\n",
            "Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in /usr/local/lib/python3.11/dist-packages (from notebook>=7.2.2->nvidia-physicsnemo-sym) (2.27.3)\n",
            "Requirement already satisfied: jupyterlab<4.5,>=4.4.3 in /usr/local/lib/python3.11/dist-packages (from notebook>=7.2.2->nvidia-physicsnemo-sym) (4.4.3)\n",
            "Requirement already satisfied: notebook-shim<0.3,>=0.2 in /usr/local/lib/python3.11/dist-packages (from notebook>=7.2.2->nvidia-physicsnemo-sym) (0.2.4)\n",
            "Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from notebook>=7.2.2->nvidia-physicsnemo-sym) (6.4.2)\n",
            "Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from numpoly<=1.3.4->nvidia-physicsnemo-sym) (8.7.0)\n",
            "Requirement already satisfied: python-utils>=3.4.5 in /usr/local/lib/python3.11/dist-packages (from numpy-stl>=2.16->nvidia-physicsnemo-sym) (3.9.1)\n",
            "Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2025.4.26)\n",
            "Requirement already satisfied: fsspec>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2025.5.1)\n",
            "Requirement already satisfied: onnx>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (1.18.0)\n",
            "Requirement already satisfied: s3fs>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2025.5.1)\n",
            "Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2.6.0+cu124)\n",
            "Requirement already satisfied: tqdm>=4.60.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (4.67.1)\n",
            "Requirement already satisfied: treelib>=1.2.5 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (1.7.1)\n",
            "Requirement already satisfied: xarray>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2025.3.1)\n",
            "Requirement already satisfied: zarr>=2.14.2 in /usr/local/lib/python3.11/dist-packages (from nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (3.0.8)\n",
            "Requirement already satisfied: platformdirs>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from pint>=0.19.2->nvidia-physicsnemo-sym) (4.3.8)\n",
            "Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from pint>=0.19.2->nvidia-physicsnemo-sym) (4.14.0)\n",
            "Requirement already satisfied: flexcache>=0.3 in /usr/local/lib/python3.11/dist-packages (from pint>=0.19.2->nvidia-physicsnemo-sym) (0.3)\n",
            "Requirement already satisfied: flexparser>=0.4 in /usr/local/lib/python3.11/dist-packages (from pint>=0.19.2->nvidia-physicsnemo-sym) (0.4)\n",
            "Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2.0->nvidia-physicsnemo-sym) (1.5.1)\n",
            "Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2.0->nvidia-physicsnemo-sym) (3.6.0)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy>=1.12->nvidia-physicsnemo-sym) (1.3.0)\n",
            "Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.8.0->nvidia-physicsnemo-sym) (1.4.0)\n",
            "Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.8.0->nvidia-physicsnemo-sym) (1.72.1)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.8.0->nvidia-physicsnemo-sym) (3.8)\n",
            "Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.8.0->nvidia-physicsnemo-sym) (5.29.5)\n",
            "Requirement already satisfied: six>1.9 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.8.0->nvidia-physicsnemo-sym) (1.17.0)\n",
            "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.8.0->nvidia-physicsnemo-sym) (0.7.2)\n",
            "Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.8.0->nvidia-physicsnemo-sym) (3.1.3)\n",
            "Requirement already satisfied: torchvision in /usr/local/lib/python3.11/dist-packages (from timm>=1.0.3->nvidia-physicsnemo-sym) (0.21.0+cu124)\n",
            "Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from timm>=1.0.3->nvidia-physicsnemo-sym) (6.0.2)\n",
            "Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.11/dist-packages (from timm>=1.0.3->nvidia-physicsnemo-sym) (0.32.4)\n",
            "Requirement already satisfied: safetensors in /usr/local/lib/python3.11/dist-packages (from timm>=1.0.3->nvidia-physicsnemo-sym) (0.5.3)\n",
            "Requirement already satisfied: pytorch-ranger>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from torch-optimizer>=0.3.0->nvidia-physicsnemo-sym) (0.1.1)\n",
            "Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from vtk>=9.2.6->nvidia-physicsnemo-sym) (3.10.0)\n",
            "Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (4.9.0)\n",
            "Requirement already satisfied: argon2-cffi>=21.1 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (25.1.0)\n",
            "Requirement already satisfied: jinja2>=3.0.3 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (3.1.6)\n",
            "Requirement already satisfied: jupyter-client>=7.4.4 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (8.6.3)\n",
            "Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (5.8.1)\n",
            "Requirement already satisfied: jupyter-events>=0.11.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.12.0)\n",
            "Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.5.3)\n",
            "Requirement already satisfied: nbconvert>=6.4.4 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (7.16.6)\n",
            "Requirement already satisfied: nbformat>=5.3.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (5.10.4)\n",
            "Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (7.7.0)\n",
            "Requirement already satisfied: prometheus-client>=0.9 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.22.1)\n",
            "Requirement already satisfied: pyzmq>=24 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (24.0.1)\n",
            "Requirement already satisfied: send2trash>=1.8.2 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.8.3)\n",
            "Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.18.1)\n",
            "Requirement already satisfied: traitlets>=5.6.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (5.7.1)\n",
            "Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.8.0)\n",
            "Requirement already satisfied: async-lru>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.0.5)\n",
            "Requirement already satisfied: httpx>=0.25.0 in /usr/local/lib/python3.11/dist-packages (from jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.28.1)\n",
            "Requirement already satisfied: ipykernel>=6.5.0 in /usr/local/lib/python3.11/dist-packages (from jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (6.17.1)\n",
            "Requirement already satisfied: jupyter-lsp>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.2.5)\n",
            "Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.11/dist-packages (from jupyterlab-server<3,>=2.27.1->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.17.0)\n",
            "Requirement already satisfied: json5>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from jupyterlab-server<3,>=2.27.1->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.12.0)\n",
            "Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.11/dist-packages (from jupyterlab-server<3,>=2.27.1->notebook>=7.2.2->nvidia-physicsnemo-sym) (4.24.0)\n",
            "Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from jupyterlab-server<3,>=2.27.1->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.32.3)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.0.0->vtk>=9.2.6->nvidia-physicsnemo-sym) (1.3.2)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.0.0->vtk>=9.2.6->nvidia-physicsnemo-sym) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.0.0->vtk>=9.2.6->nvidia-physicsnemo-sym) (4.58.1)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.0.0->vtk>=9.2.6->nvidia-physicsnemo-sym) (1.4.8)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.0.0->vtk>=9.2.6->nvidia-physicsnemo-sym) (3.2.3)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.0.0->vtk>=9.2.6->nvidia-physicsnemo-sym) (2.9.0.post0)\n",
            "Requirement already satisfied: aiobotocore<3.0.0,>=2.5.4 in /usr/local/lib/python3.11/dist-packages (from s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2.22.0)\n",
            "Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (3.11.15)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (3.18.0)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (3.5)\n",
            "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (12.4.127)\n",
            "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (12.4.127)\n",
            "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (12.4.127)\n",
            "Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (9.1.0.70)\n",
            "Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (12.4.5.8)\n",
            "Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (11.2.1.3)\n",
            "Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (10.3.5.147)\n",
            "Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (11.6.1.9)\n",
            "Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (12.3.1.170)\n",
            "Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (0.6.2)\n",
            "Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2.21.5)\n",
            "Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (12.4.127)\n",
            "Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (12.4.127)\n",
            "Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.4.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (3.2.0)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard>=2.8.0->nvidia-physicsnemo-sym) (3.0.2)\n",
            "Requirement already satisfied: pandas>=2.1 in /usr/local/lib/python3.11/dist-packages (from xarray>=2023.1.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2.2.2)\n",
            "Requirement already satisfied: donfig>=0.8 in /usr/local/lib/python3.11/dist-packages (from zarr>=2.14.2->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (0.8.1.post1)\n",
            "Requirement already satisfied: numcodecs>=0.14 in /usr/local/lib/python3.11/dist-packages (from numcodecs[crc32c]>=0.14->zarr>=2.14.2->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (0.16.1)\n",
            "Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->timm>=1.0.3->nvidia-physicsnemo-sym) (1.1.2)\n",
            "Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->numpoly<=1.3.4->nvidia-physicsnemo-sym) (3.22.0)\n",
            "Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (0.12.0)\n",
            "Requirement already satisfied: botocore<1.37.4,>=1.37.2 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (1.37.3)\n",
            "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (1.0.1)\n",
            "Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (6.4.4)\n",
            "Requirement already satisfied: wrapt<2.0.0,>=1.10.10 in /usr/local/lib/python3.11/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (1.17.2)\n",
            "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2.6.1)\n",
            "Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (1.3.2)\n",
            "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (25.3.0)\n",
            "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (1.6.0)\n",
            "Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (0.3.1)\n",
            "Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.5.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (1.20.0)\n",
            "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (3.10)\n",
            "Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.3.1)\n",
            "Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.11/dist-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (21.2.0)\n",
            "Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.25.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.0.9)\n",
            "Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.16.0)\n",
            "Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.8.0)\n",
            "Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (7.34.0)\n",
            "Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.1.7)\n",
            "Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.6.0)\n",
            "Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (5.9.5)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=7.2.2->nvidia-physicsnemo-sym) (2025.4.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.36.2)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.25.1)\n",
            "Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.11/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (3.3.0)\n",
            "Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.11/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.1.4)\n",
            "Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.1.1)\n",
            "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (4.13.4)\n",
            "Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.11/dist-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (6.2.0)\n",
            "Requirement already satisfied: defusedxml in /usr/local/lib/python3.11/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.7.1)\n",
            "Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.11/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.3.0)\n",
            "Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.10.2)\n",
            "Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.5.1)\n",
            "Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.19.1)\n",
            "Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.11/dist-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.21.1)\n",
            "Requirement already satisfied: crc32c>=2.7 in /usr/local/lib/python3.11/dist-packages (from numcodecs[crc32c]>=0.14->zarr>=2.14.2->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2.7.1)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.1->xarray>=2023.1.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.1->xarray>=2023.1.0->nvidia-physicsnemo>=1.0.0->nvidia-physicsnemo-sym) (2025.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook>=7.2.2->nvidia-physicsnemo-sym) (3.4.2)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.4.0)\n",
            "Requirement already satisfied: ptyprocess in /usr/local/lib/python3.11/dist-packages (from terminado>=0.8.3->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.7.0)\n",
            "Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.5.1)\n",
            "Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.4.0)\n",
            "Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.19.2)\n",
            "Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (4.4.2)\n",
            "Requirement already satisfied: pickleshare in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.7.5)\n",
            "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (3.0.51)\n",
            "Requirement already satisfied: backcall in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.2.0)\n",
            "Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (4.9.0)\n",
            "Requirement already satisfied: fqdn in /usr/local/lib/python3.11/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.5.1)\n",
            "Requirement already satisfied: isoduration in /usr/local/lib/python3.11/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (20.11.0)\n",
            "Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.11/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (3.0.0)\n",
            "Requirement already satisfied: uri-template in /usr/local/lib/python3.11/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.3.0)\n",
            "Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (24.11.1)\n",
            "Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.17.1)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.7)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.22)\n",
            "Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.11/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.8.4)\n",
            "Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook>=7.2.2->nvidia-physicsnemo-sym) (0.2.13)\n",
            "Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.11/dist-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (1.3.0)\n",
            "Requirement already satisfied: types-python-dateutil>=2.8.10 in /usr/local/lib/python3.11/dist-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=7.2.2->nvidia-physicsnemo-sym) (2.9.0.20250516)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "### FNOを使用したDarcyFlowの学習のexampleの実行（physicsnemo）"
      ],
      "metadata": {
        "id": "KSuYzvPe4_Ij"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "%cd \"/content/drive/MyDrive/physicsnemo_workspace/physicsnemo/examples/cfd/darcy_fno\"\n",
        "!pip install -r requirements.txt\n",
        "!python train_fno_darcy.py"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "1cD87CmO712u",
        "outputId": "ca61ac94-e416-4eae-92cd-57d72f3033e4"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content/drive/MyDrive/physicsnemo_workspace/physicsnemo/examples/cfd/darcy_fno\n",
            "Requirement already satisfied: hydra-core>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 1)) (1.3.2)\n",
            "Requirement already satisfied: mlflow>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 2)) (3.1.0)\n",
            "Requirement already satisfied: warp-lang>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 3)) (1.7.2)\n",
            "Requirement already satisfied: termcolor>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 4)) (3.1.0)\n",
            "Requirement already satisfied: omegaconf<2.4,>=2.2 in /usr/local/lib/python3.11/dist-packages (from hydra-core>=1.2.0->-r requirements.txt (line 1)) (2.3.0)\n",
            "Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.11/dist-packages (from hydra-core>=1.2.0->-r requirements.txt (line 1)) (4.9.3)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from hydra-core>=1.2.0->-r requirements.txt (line 1)) (24.2)\n",
            "Requirement already satisfied: mlflow-skinny==3.1.0 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (3.1.0)\n",
            "Requirement already satisfied: Flask<4 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (3.1.1)\n",
            "Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (1.16.1)\n",
            "Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (7.1.0)\n",
            "Requirement already satisfied: graphene<4 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (3.4.3)\n",
            "Requirement already satisfied: gunicorn<24 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (23.0.0)\n",
            "Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (3.10.0)\n",
            "Requirement already satisfied: numpy<3 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (2.0.2)\n",
            "Requirement already satisfied: pandas<3 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (2.2.2)\n",
            "Requirement already satisfied: pyarrow<21,>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (18.1.0)\n",
            "Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (1.6.1)\n",
            "Requirement already satisfied: scipy<2 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (1.15.3)\n",
            "Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.1.1->-r requirements.txt (line 2)) (2.0.41)\n",
            "Requirement already satisfied: cachetools<7,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (5.5.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (8.2.1)\n",
            "Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.1.1)\n",
            "Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.56.0)\n",
            "Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.115.12)\n",
            "Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.1.44)\n",
            "Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (8.7.0)\n",
            "Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (1.34.1)\n",
            "Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (1.34.1)\n",
            "Requirement already satisfied: protobuf<7,>=3.12.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (5.29.5)\n",
            "Requirement already satisfied: pydantic<3,>=1.10.8 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (2.11.5)\n",
            "Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (6.0.2)\n",
            "Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (2.32.3)\n",
            "Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.5.3)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (4.14.0)\n",
            "Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.34.3)\n",
            "Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic!=1.10.0,<2->mlflow>=2.1.1->-r requirements.txt (line 2)) (1.1.3)\n",
            "Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from docker<8,>=4.0.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (2.4.0)\n",
            "Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (1.9.0)\n",
            "Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (2.2.0)\n",
            "Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.1.6)\n",
            "Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.0.2)\n",
            "Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.1.3)\n",
            "Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.11/dist-packages (from graphene<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.2.6)\n",
            "Requirement already satisfied: graphql-relay<3.3,>=3.1 in /usr/local/lib/python3.11/dist-packages (from graphene<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.2.0)\n",
            "Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.11/dist-packages (from graphene<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (2.9.0.post0)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (1.3.2)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (4.58.1)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (1.4.8)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (11.2.1)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.2.3)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3->mlflow>=2.1.1->-r requirements.txt (line 2)) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3->mlflow>=2.1.1->-r requirements.txt (line 2)) (2025.2)\n",
            "Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<2->mlflow>=2.1.1->-r requirements.txt (line 2)) (1.5.1)\n",
            "Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<2->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.6.0)\n",
            "Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.2.2)\n",
            "Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.11/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (2.38.0)\n",
            "Requirement already satisfied: starlette<0.47.0,>=0.40.0 in /usr/local/lib/python3.11/dist-packages (from fastapi<1->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.46.2)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (4.0.12)\n",
            "Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.22.0)\n",
            "Requirement already satisfied: opentelemetry-semantic-conventions==0.55b1 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.55b1)\n",
            "Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.7.0)\n",
            "Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (2.33.2)\n",
            "Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.4.1)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow>=2.1.1->-r requirements.txt (line 2)) (1.17.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.4.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (3.10)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (2025.4.26)\n",
            "Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/dist-packages (from uvicorn<1->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.16.0)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (5.0.2)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.4.2)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (4.9.1)\n",
            "Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.11/dist-packages (from starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (4.9.0)\n",
            "Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (1.3.1)\n",
            "Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow>=2.1.1->-r requirements.txt (line 2)) (0.6.1)\n",
            "Warp CUDA error: Could not open libcuda.so.\n",
            "Warp CUDA error: Function cuDriverGetVersion_f: a suitable driver entry point was not found\n",
            "Warp CUDA error 36 (in function cuda_driver_version, /builds/omniverse/warp/warp/native/warp.cu:1719)\n",
            "Warp 1.7.2 initialized:\n",
            "   CUDA Toolkit 12.8, Driver 0.0 (insufficient CUDA driver version!)\n",
            "   Devices:\n",
            "     \"cpu\"      : \"x86_64\"\n",
            "   Kernel cache:\n",
            "     /root/.cache/warp/1.7.2\n",
            "Warp UserWarning: \n",
            "   Insufficient CUDA driver version.\n",
            "   The minimum required CUDA driver version is 12.0, but the installed CUDA driver version is 0.0.\n",
            "   Visit https://github.com/NVIDIA/warp/blob/main/README.md#installing for guidance.\n",
            "/usr/local/lib/python3.11/dist-packages/physicsnemo/distributed/manager.py:415: UserWarning: Could not initialize using ENV, SLURM or OPENMPI methods. Assuming this is a single process job\n",
            "  warn(\n",
            "2025/06/11 04:14:05 WARNING mlflow: \u001b[93mChecking MLFlow logging location is working (if this hangs it's not)\u001b[0m\n",
            "2025/06/11 04:14:05 ERROR mlflow: \u001b[91mFailed to validate MLFlow logging location works\u001b[0m\n",
            "Error executing job with overrides: []\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/drive/MyDrive/physicsnemo_workspace/physicsnemo/examples/cfd/darcy_fno/train_fno_darcy.py\", line 53, in darcy_trainer\n",
            "    initialize_mlflow(\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/physicsnemo/launch/logging/mlflow.py\", line 134, in initialize_mlflow\n",
            "    check_mlflow_logged_in(client)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/physicsnemo/launch/logging/mlflow.py\", line 190, in check_mlflow_logged_in\n",
            "    raise e\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/physicsnemo/launch/logging/mlflow.py\", line 185, in check_mlflow_logged_in\n",
            "    experiment = client.create_experiment(\"test\")\n",
            "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mlflow/tracking/client.py\", line 1786, in create_experiment\n",
            "    return self._tracking_client.create_experiment(name, artifact_location, tags)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mlflow/tracking/_tracking_service/client.py\", line 275, in create_experiment\n",
            "    return self.store.create_experiment(\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mlflow/store/tracking/file_store.py\", line 429, in create_experiment\n",
            "    self._validate_experiment_does_not_exist(name)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mlflow/store/tracking/file_store.py\", line 409, in _validate_experiment_does_not_exist\n",
            "    raise MlflowException(\n",
            "mlflow.exceptions.MlflowException: Experiment 'test' already exists in deleted state. You can restore the experiment, or permanently delete the experiment from the .trash folder (under tracking server's root folder) in order to use this experiment name again.\n",
            "\n",
            "Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "### physicsnemo-sym"
      ],
      "metadata": {
        "id": "9MtAE7Zx7ksF"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "GPUの使用制限によりテストできず"
      ],
      "metadata": {
        "id": "g5awyQPII-bn"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "%cd \"/content/drive/MyDrive/physicsnemo_workspace/physicsnemo-sym/examples/ldc/\"\n",
        "!python ldc_2d.py"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "whNXxS_I7nvj",
        "outputId": "1366dd7e-e32f-4363-ee2e-40991f0ffc3c"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content/drive/MyDrive/physicsnemo_workspace/physicsnemo-sym/examples/ldc\n",
            "2025-06-11 04:14:14.713664: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
            "E0000 00:00:1749615254.737416    2952 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "E0000 00:00:1749615254.744588    2952 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2025-06-11 04:14:14.768029: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "/usr/local/lib/python3.11/dist-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.\n",
            "See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.\n",
            "  ret = run_job(\n",
            "[W611 04:14:21.512514290 init.cpp:779] Warning: nvfuser is no longer supported in torch script, use _jit_set_nvfuser_single_node_mode is deprecated and a no-op (function operator())\n",
            "[W611 04:14:21.512566166 init.cpp:767] Warning: nvfuser is no longer supported in torch script, use _jit_set_nvfuser_enabled is deprecated and a no-op (function operator())\n",
            "[04:14:21] - JIT using the NVFuser TorchScript backend\n",
            "[04:14:21] - Disabling JIT because functorch does not work with it.\n",
            "[04:14:21] - JitManager: {'_enabled': False, '_arch_mode': <JitArchMode.ONLY_ACTIVATION: 1>, '_use_nvfuser': True, '_autograd_nodes': False}\n",
            "[04:14:21] - GraphManager: {'_func_arch': True, '_debug': False, '_func_arch_allow_partial_hessian': True}\n",
            "[04:14:21] - AmpManager: {'_enabled': False, '_mode': <AmpMode.PER_ORDER_SCALER: 0>, '_dtype': torch.float16, '_default_max_scale': 1, '_autocast_activation': False, '_autocast_firstlayer': False, '_special_terms': [], '_custom_max_scales': {}}\n",
            "[04:14:27] - Arch Node: flow_network has been converted to a FuncArch node.\n",
            "/content/drive/MyDrive/physicsnemo_workspace/physicsnemo-sym/examples/ldc/ldc_2d.py:130: UserWarning: Directory openfoam/cavity_uniformVel0.csv does not exist. Will skip adding validators. Please download the additional files from NGC https://catalog.ngc.nvidia.com/orgs/nvidia/teams/physicsnemo/resources/physicsnemo_sym_examples_supplemental_materials\n",
            "  warnings.warn(\n",
            "[04:14:27] - Installed PyTorch version 2.6.0+cu124 is not TorchScript supported in PhysicsNeMo. Version 2.1.0a0+4136153 is officially supported.\n",
            "/usr/local/lib/python3.11/dist-packages/physicsnemo/sym/amp.py:221: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.\n",
            "  super().__init__(*args, **kwargs)\n",
            "[04:14:27] - attempting to restore from: outputs/ldc_2d\n",
            "[04:14:27] - optimizer checkpoint not found\n",
            "[04:14:27] - model flow_network.0.pth not found\n",
            "Error executing job with overrides: []\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/drive/MyDrive/physicsnemo_workspace/physicsnemo-sym/examples/ldc/ldc_2d.py\", line 138, in run\n",
            "    slv.solve()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/physicsnemo/sym/solver/solver.py\", line 182, in solve\n",
            "    self._train_loop(sigterm_handler)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/physicsnemo/sym/trainer.py\", line 649, in _train_loop\n",
            "    loss, losses = self._cuda_graph_training_step(step)\n",
            "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/physicsnemo/sym/trainer.py\", line 847, in _cuda_graph_training_step\n",
            "    self.warmup_stream = torch.cuda.Stream()\n",
            "                         ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/cuda/streams.py\", line 34, in __new__\n",
            "    return super().__new__(cls, priority=priority, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "RuntimeError: CUDA error: CUDA driver version is insufficient for CUDA runtime version\n",
            "CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\n",
            "For debugging consider passing CUDA_LAUNCH_BLOCKING=1\n",
            "Device-side assertions were explicitly omitted for this error check; the error probably arose while initializing the DSA handlers.\n",
            "\n",
            "Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.\n"
          ]
        }
      ]
    }
  ]
}